dumps:
    path: ./dumps
    weights: weights
    logs: logs

epochs: &epochs 40
batch_size: &batch_size 3
num_workers: &num_workers 2
num_classes: &num_classes 1

train_params:
    gpu_id: 0
    num_workers: *num_workers
    batch_size: *batch_size  
    num_epochs: *epochs
    num_folds: 4
    fold: 3
    lr: 1e-3

data_params:
    data_folder: /home/nzhao/Documents/PJ_Pelvis/main/data/hiatus
    batch_size: *batch_size 
    num_workers: *num_workers
    

MODEL:
  NAME: seg_hrnet
  PRETRAINED: /home/nzhao/Documents/PJ_Pelvis/main/dumps/weights
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM

