dumps:
    path: ./dumps
    weights: weights
    logs: logs

epochs: &epochs 40
batch_size: &batch_size 6
num_workers: &num_workers 2

train_params:
    gpu_id: 0
    num_workers: *num_workers
    batch_size: *batch_size  
    num_epochs: *epochs
    num_folds: 4
    fold: 0
    lr: 1e-3

data_params:
    data_folder: xxx
    batch_size: *batch_size 
    num_workers: *num_workers

